version: '3'
services:
  simpleserverz:
    image: simpleserverz
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simpleserverz
    ports:
      - "3000:80"  
    environment:
      - PORT=80
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
